### ISSUE TITLE
Using/playing against trained DQN model

### ISSUE THREAD

**Issue by Rice-Field-Memes** [datamllab/rlcard#209]
I used uno_dqn.py to generate a Q model for Uno. I have looked through the documentation and can't seem to figure out how to utilize the model I created. In my case, I am planning on using the DQN with the uno_human.py, and allow a human to play against a Q network instead of the rule model. At first I tried to add the model to the pretrained folder, and add it to pretrained_models.py as recommended by #112 , but this hasn't been working with a DQN model.

**Comment by daochenzha** [comment]
@Rice-Field-Memes Could you share the specific errors you met?

**Comment by Rice-Field-Memes** [comment]
This is the error when I try to run the uno_human when loading the pretrained model
`WARNING:tensorflow:From D:\Documents\rlcard_venv\rlcard\models\uno_dqn.py:44: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2021-02-24 08:44:42.249290: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key beta1_power_2 not found in checkpoint
Traceback (most recent call last):
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key beta1_power_2 not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key beta1_power_2 not found in checkpoint
         [[node save/RestoreV2 (defined at D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "uno_vs.py", line 13, in <module>
    dqn_agent = models.load('uno-dqn').agents[0]
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 77, in load
    return model_registry.load(model_id)
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 56, in load
    return self.model_specs[model_id].load()
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 24, in load
    model = self._entry_point()
  File "D:\Documents\rlcard_venv\rlcard\models\uno_dqn.py", line 44, in __init__
    saver = tf.train.Saver()
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uno_vs.py", line 13, in <module>
    dqn_agent = models.load('uno-dqn').agents[0]
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 77, in load
    return model_registry.load(model_id)
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 56, in load
    return self.model_specs[model_id].load()
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 24, in load
    model = self._entry_point()
  File "D:\Documents\rlcard_venv\rlcard\models\uno_dqn.py", line 46, in __init__
    saver.restore(self.sess, tf.train.latest_checkpoint(check_point_path))
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key beta1_power_2 not found in checkpoint
         [[node save/RestoreV2 (defined at D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "uno_vs.py", line 13, in <module>
    dqn_agent = models.load('uno-dqn').agents[0]
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 77, in load
    return model_registry.load(model_id)
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 56, in load
    return self.model_specs[model_id].load()
  File "D:\Documents\rlcard_venv\rlcard\models\registration.py", line 24, in load
    model = self._entry_point()
  File "D:\Documents\rlcard_venv\rlcard\models\uno_dqn.py", line 44, in __init__
    saver = tf.train.Saver()
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "D:\Documents\rlcard_venv\env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()`

This is the first part of the code:
`import tensorflow as tf
import rlcard
from rlcard import models
from rlcard.agents import DQNAgent
from rlcard.agents.uno_human_agent import HumanAgent, _print_action

# Make environment and enable human mode
# Set 'record_action' to True because we need it to print results
env = rlcard.make('uno', config={'record_action': True})
human_agent = HumanAgent(env.action_num)
dqn_agent = models.load('uno-dqn').agents[0]
env.set_agents([human_agent, dqn_agent])`

Just in case, this is the model class for Uno DQN

`import os

import rlcard
from rlcard.agents import CFRAgent
from rlcard.agents import DQNAgent
from rlcard.models.model import Model

# Root path of pretrianed models
ROOT_PATH = os.path.join(rlcard.__path__[0], 'models\pretrained')

class UnoDQNModel(Model):
    ''' A pretrained model on Uno with DQN
    '''

    def __init__(self):
        ''' Load pretrained model
        '''
        import tensorflow as tf
        from rlcard.agents import DQNAgent
        #tf.compat.v1.global_variables_initializer()
        #tf.compat.v1.local_variables_initializer()
        
        env = rlcard.make('uno')
        
        self.graph = tf.Graph()
        self.sess = tf.Session(graph=self.graph)
        

        with self.graph.as_default():

            self.dqn_agents = []
            for i in range(env.player_num):
                agent = DQNAgent(self.sess,
                    scope='dqn' + str(i),
                    action_num=env.action_num,
                    state_shape=env.state_shape,
                    mlp_layers=[512,512])
                self.dqn_agents.append(agent)
        
       
        check_point_path = os.path.join(ROOT_PATH, 'uno_dqn')
        with self.sess.as_default():
            with self.graph.as_default():
                saver = tf.train.Saver()
#                saver = tf.train.Saver()
                saver.restore(self.sess, tf.train.latest_checkpoint(check_point_path))
        
        
        
    @property
    def agents(self):
        ''' Get a list of agents for each position in a the game

        Returns:
            agents (list): A list of agents

        Note: Each agent should be just like RL agent with step and eval_step
              functioning well.
        '''
        return self.dqn_agents`

**Comment by daochenzha** [comment]
@Rice-Field-Memes Hi, it is still difficult for me to reproduce this error since we do not have a uno DQN model. Could you fork RLCard in your GitHub and upload your code so that I can take a look? Thanks!

**Comment by Rice-Field-Memes** [comment]
Ok. I forked it [here](https://github.com/Rice-Field-Memes/rlcard).
I used a python virtual environment, the list of packages I installed is at envListPackages.txt
The uno dqn model is at /models/ and /rlcard/models/pretrained/
The file I used to play human against DQN is uno_vs.py
Thank you very much for your help

**Comment by Rice-Field-Memes** [comment]
Also, I am planning on applying this trained model to play on a remote server, without perfecting information. If I needed to utilize the AI in a setting with imperfect information, would I have to modify the uno environment and game that is included in rlcard? Thank you again

**Comment by daochenzha** [comment]
@Rice-Field-Memes The UNO environment is RLCard is imperfect information, which means others' hand is know shown in the state representations. For your code, we are still checking what the issue is. We will let you know.

**Comment by Rice-Field-Memes** [comment]
Thank you, but perhaps I am misunderstanding. I knew that the Uno state representation included the other's hand, but I thought this would mean it is perfect information, because the AI has access to all the information in its state. And when I said imperfect information, I was thinking a state representation with only the AI's hand, the target card, and possibly the amount of cards the opponent's hand has, without the AI knowing what cards the opponent has. Very sorry for the trouble, and I appreciate your help.

**Comment by daochenzha** [comment]
@Rice-Field-Memes Thanks for pointing this out! Yes, the other's hand indeed makes it perfect information. It should be a bug and we will fix it.

**Comment by Rice-Field-Memes** [comment]
@daochenzha No problem. Also, I believe I fixed the problem I had with loading the Uno DQN. In the model class, I needed to remove the for loop in __init__ that would several agents based on the player_num. Because the DQN model was trained with only one agent against a random agent, the model loading failed to find variables for multiple agents.
Once again, I appreciate the help and I appreciate the bug with imperfect-information being looked into.

**Comment by lhenry15** [comment]
Thank you for letting us know. 

The problem that DQN cannot be applied in multiple agent environment is because our implementation does not involve the Adam Optimizer in any scope, we just simply name it with "dqn_adam". 

And since there is a placeholder in Adam Optimizer (beta1_power and beta2_power for decay ratio), if there are multiple DQNs during the runtime (when you initialize them in the uno_loadmodel.py), the placeholders will be automatically renamed as (beta1_power_1/beta1_power_2).

However, we didn't design the DQN for multi-player scenario, which means in your pretrained model, there will only be one beta1_power (even if you train multiple DQN agent simultaneously), and therefore the newly initialized DQN agent with Adam's placeholders(beta1_power_1/beta1_power_2) will not able to find its pretrained weight.

If you want to allow the DQN agent to train in a multi-player fashion, you might want to take a look into this line of code, and add scope and rename the Adam optimizer for each DQN agent, so that the place holder for the decay ratio in Adam optimizer will not be renamed.
https://github.com/datamllab/rlcard/blob/328175f5a81c3b67eb3882faa63f26db799fefc6/rlcard/agents/dqn_agent.py#L244

**Comment by CaoYuanpu** [comment]
@Rice-Field-Memes Thanks point out the bug in UNO. 
We have removed `others hand` in the state representation of UNO and made it imperfection env.
cc @daochenzha
