### ISSUE TITLE
Tensorflow require even if PyTorch is used?

### ISSUE THREAD

**Issue by FranzPfeifroth** [datamllab/rlcard#217]
I try to run the example leduce_holdem_nfsp_pytorch using PyCharm.  After installing torch and rlcard I got the following output:

D:\AI\Python\Leduce_holdem_nfsp_pytorch\venv\Scripts\python.exe D:/AI/Python/Leduce_holdem_nfsp_pytorch/Source/nfsp_pytorch.py
Traceback (most recent call last):
  File "D:/AI/Python/Leduce_holdem_nfsp_pytorch/Source/nfsp_pytorch.py", line 7, in <module>
    from rlcard.agents import NFSPAgentPytorch as NFSPAgent
  File "D:\AI\Python\Leduce_holdem_nfsp_pytorch\venv\lib\site-packages\rlcard\agents\__init__.py", line 17, in <module>
    from rlcard.agents.dqn_agent_pytorch import DQNAgent as DQNAgentPytorch
  File "D:\AI\Python\Leduce_holdem_nfsp_pytorch\venv\lib\site-packages\rlcard\agents\dqn_agent_pytorch.py", line 34, in <module>
    from rlcard.agents.dqn_agent import Memory
  File "D:\AI\Python\Leduce_holdem_nfsp_pytorch\venv\lib\site-packages\rlcard\agents\dqn_agent.py", line 29, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Question: Do I need to install tensorforce too?

**Comment by daochenzha** [comment]
@FranzPfeifroth Thanks for the feedback. You may try this branch where we cleanly removed tf. https://github.com/datamllab/rlcard/tree/dmc

**Comment by FranzPfeifroth** [comment]
Thanks, this works fine.

**Comment by daochenzha** [comment]
@FranzPfeifroth Thanks for the feedback anyway! We will fix it.
