### ISSUE TITLE
Can you help to use "Pystack" on Github?

### ISSUE THREAD

**Issue by LizChen2000** [datamllab/rlcard#235]

**Comment by LizChen2000** [comment]
I have been contact with the author,but nothing reply~
And I saw you leave comments on it. So I can here to ask for help
My problem is when I run"python train_nn.py --street 4 --approximate root_nodes"
it will 
"Traceback (most recent call last):
  File "train_nn.py", line 38, in <module>
    main()
  File "train_nn.py", line 35, in main
    T.train(num_epochs=arguments.num_epochs, batch_size=arguments.batch_size, validation_size=0.1, start_epoch=starting_idx)
  File "F:\PyStack-texas-holdem\src\NnTraining\train.py", line 68, in train
    callbacks = self.callbacks, initial_epoch = start_epoch )
  File "F:\Anaconda\envs\texas\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "F:\Anaconda\envs\texas\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 346, in model_iteration
    aggregator.finalize()
  File "F:\Anaconda\envs\texas\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 108, in finalize
    self.results[0] /= self.num_samples_or_steps
IndexError: list index out of range"
I use python=3.6,tensorflow=1.13.1
If you can help me,I truly appreciate your support!!
