### ISSUE TITLE
Doc search is broken

### ISSUE THREAD

**Issue by wlnirvana** [datamllab/rlcard#290]
Search is stuck at this step, never updating:

<img width="1149" alt="image" src="https://github.com/datamllab/rlcard/assets/3822785/9221d3df-6968-460f-8d88-b781b7bc2583">

The stack trace of the error logged out in developer console is:

```
 is not defined
    at Object.query (searchtools.js:158:19)
    at Object.setIndex (searchtools.js:98:14)
    at <anonymous>:1:8
    at b (jquery.js:2:839)
    at Function.globalEval (jquery.js:2:2878)
    at text script (jquery.js:2:82979)
    at jquery.js:2:79369
    at l (jquery.js:2:79486)
    at XMLHttpRequest.<anonymous> (jquery.js:2:82254)
```

Might be related to sphinx-doc/sphinx#8623

**Comment by hsywhu** [comment]
Thanks for reporting the issue, the doc site is updated and the searching functionality is fixed
