### ISSUE TITLE
执行run_rl.py报错

### ISSUE THREAD

**Issue by skgdz** [datamllab/rlcard#293]
部署rlcard 后 尝试运行run_rl.py 报错 麻烦问一下 该如何处理
root@ip:~/rlcard/examples# python3 run_rl.py
--> Running on the CPU

Logs saved in experiments/leduc_holdem_dqn_result/
Traceback (most recent call last):
  File "run_rl.py", line 181, in <module>
    train(args)
  File "run_rl.py", line 92, in train
    tournament(
  File "/root/rlcard/rlcard/utils/utils.py", line 210, in tournament
    _, _payoffs = env.run(is_training=False)
  File "/root/rlcard/rlcard/envs/env.py", line 149, in run
    next_state, next_player_id = self.step(action, self.agents[player_id].use_raw)
AttributeError: 'DQNAgent' object has no attribute 'use_raw'

**Comment by daochenzha** [comment]
@skgdz It is a bug. I have fixed it in the latest commit.

**Comment by skgdz** [comment]
OK  thank you
